# Generated by Django 4.0.3 on 2022-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='matni',
            field=models.TextField(default=11111),
            preserve_default=False,
        ),
    ]
