# Generated by Django 4.0.3 on 2022-03-31 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ev'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('ownership', models.IntegerField()),
                ('bev_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mamlakat', to='core.ev')),
            ],
            options={
                'verbose_name': 'Davlat xalqi',
                'verbose_name_plural': 'Davlatlar xalqlari',
            },
        ),
    ]
